// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bklwxaqaveroukujwqaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbHd4YXFhdmVyb3VrdWp3cWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjQ1MzksImV4cCI6MjA2Nzk0MDUzOX0.-9U7q0ES0m9u70V_bf1F3bEhf1ivYmjygEOd0DEVFas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});